import type { Metadata } from "next";
import "./globals.css"
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata:Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
